<?php

namespace ContainerR8keNxw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aREs5yN.App\Controller\CategoriesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aREs5yN.App\\Controller\\CategoriesController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'categories' => ['privates', '.errored..service_locator.aREs5yN.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.aREs5yN": it needs an instance of "App\\Entity\\Categories" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'categories' => 'App\\Entity\\Categories',
        ]))->withContext('App\\Controller\\CategoriesController::edit()', $container);
    }
}
