<?php

namespace ContainerIxQHxSI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75P59IX.App\Controller\CommandeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.75P59IX.App\\Controller\\CommandeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
        ]))->withContext('App\\Controller\\CommandeController::index()', $container);
    }
}
