<?php

namespace ContainerIxQHxSI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Tyk8_y.App\Controller\LivreController::all()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Tyk8_y.App\\Controller\\LivreController::all()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rep' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'rep' => 'App\\Repository\\LivreRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\LivreController::all()', $container);
    }
}
