<?php

namespace Container9AdRaLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7hxiCAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7hxiC_a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7hxiC_a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoriesController::index' => ['privates', '.service_locator.BWSQ.0S.App\\Controller\\CategoriesController::index()', 'getCategoriesControllerindexService', true],
            'App\\Controller\\CategoriesController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoriesController::create()', 'getCategoriesControllercreateService', true],
            'App\\Controller\\CategoriesController::edit' => ['privates', '.service_locator.aREs5yN.App\\Controller\\CategoriesController::edit()', 'getCategoriesControllereditService', true],
            'App\\Controller\\LivreController::delete' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\LivreController::all' => ['privates', '.service_locator.5Tyk8_y.App\\Controller\\LivreController::all()', 'getLivreControllerallService', true],
            'App\\Controller\\LivreController::show2' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show2()', 'getLivreControllershow2Service', true],
            'App\\Controller\\LivreController::show3' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show3()', 'getLivreControllershow3Service', true],
            'App\\Controller\\LivreController::show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\LivreController::create()', 'getLivreControllercreateService', true],
            'App\\Controller\\LivreController::edit' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::edit()', 'getLivreControllereditService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.vPVKT.B.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoriesController:index' => ['privates', '.service_locator.BWSQ.0S.App\\Controller\\CategoriesController::index()', 'getCategoriesControllerindexService', true],
            'App\\Controller\\CategoriesController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoriesController::create()', 'getCategoriesControllercreateService', true],
            'App\\Controller\\CategoriesController:edit' => ['privates', '.service_locator.aREs5yN.App\\Controller\\CategoriesController::edit()', 'getCategoriesControllereditService', true],
            'App\\Controller\\LivreController:delete' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\LivreController:all' => ['privates', '.service_locator.5Tyk8_y.App\\Controller\\LivreController::all()', 'getLivreControllerallService', true],
            'App\\Controller\\LivreController:show2' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show2()', 'getLivreControllershow2Service', true],
            'App\\Controller\\LivreController:show3' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show3()', 'getLivreControllershow3Service', true],
            'App\\Controller\\LivreController:show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\LivreController::create()', 'getLivreControllercreateService', true],
            'App\\Controller\\LivreController:edit' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::edit()', 'getLivreControllereditService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.vPVKT.B.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoriesController::index' => '?',
            'App\\Controller\\CategoriesController::create' => '?',
            'App\\Controller\\CategoriesController::edit' => '?',
            'App\\Controller\\LivreController::delete' => '?',
            'App\\Controller\\LivreController::all' => '?',
            'App\\Controller\\LivreController::show2' => '?',
            'App\\Controller\\LivreController::show3' => '?',
            'App\\Controller\\LivreController::show' => '?',
            'App\\Controller\\LivreController::create' => '?',
            'App\\Controller\\LivreController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoriesController:index' => '?',
            'App\\Controller\\CategoriesController:create' => '?',
            'App\\Controller\\CategoriesController:edit' => '?',
            'App\\Controller\\LivreController:delete' => '?',
            'App\\Controller\\LivreController:all' => '?',
            'App\\Controller\\LivreController:show2' => '?',
            'App\\Controller\\LivreController:show3' => '?',
            'App\\Controller\\LivreController:show' => '?',
            'App\\Controller\\LivreController:create' => '?',
            'App\\Controller\\LivreController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
