<?php

namespace ContainerOxVTEVw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllersuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J_laEB8.App\Controller\PaymentController::success()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J_laEB8.App\\Controller\\PaymentController::success()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.J_laEB8.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.J_laEB8": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'em' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\PaymentController::success()', $container);
    }
}
