<?php

namespace ContainerQtx5kgl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CGpsD3F.App\Controller\LivreController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livre' => ['privates', '.errored..service_locator.CGpsD3F.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.CGpsD3F": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'livre' => 'App\\Entity\\Livre',
        ]))->withContext('App\\Controller\\LivreController::delete()', $container);
    }
}
