<?php

namespace ContainerQtx5kgl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllershow3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bWeTQZr.App\Controller\LivreController::show3()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bWeTQZr.App\\Controller\\LivreController::show3()'] = ($container->privates['.service_locator.bWeTQZr'] ?? $container->load('get_ServiceLocator_BWeTQZrService'))->withContext('App\\Controller\\LivreController::show3()', $container);
    }
}
