<?php

namespace Container4mZRs0H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ikQfIPI.App\Controller\CommandeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ikQfIPI.App\\Controller\\CommandeController::show()'] = ($container->privates['.service_locator.ikQfIPI'] ?? $container->load('get_ServiceLocator_IkQfIPIService'))->withContext('App\\Controller\\CommandeController::show()', $container);
    }
}
