<?php

namespace Container4mZRs0H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllershow2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x_5WTXf.App\Controller\UserController::show2()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x_5WTXf.App\\Controller\\UserController::show2()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.x_5WTXf.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.x_5WTXf": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'comrep' => ['privates', 'App\\Repository\\CommandeLivreRepository', 'getCommandeLivreRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'comrep' => 'App\\Repository\\CommandeLivreRepository',
        ]))->withContext('App\\Controller\\UserController::show2()', $container);
    }
}
