<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JJdXNaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jJdX_Na' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jJdX_Na'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.jJdX_Na.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.jJdX_Na": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'em' => '?',
        ]);
    }
}
