<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControlleruserindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BWSQ.0S.App\Controller\CategoriesController::userindex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BWSQ.0S.App\\Controller\\CategoriesController::userindex()'] = ($container->privates['.service_locator.BWSQ.0S'] ?? $container->load('get_ServiceLocator_BWSQ_0SService'))->withContext('App\\Controller\\CategoriesController::userindex()', $container);
    }
}
