<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControlleruserindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75P59IX.App\Controller\CommandeController::userindex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.75P59IX.App\\Controller\\CommandeController::userindex()'] = ($container->privates['.service_locator.75P59IX'] ?? $container->load('get_ServiceLocator_75P59IXService'))->withContext('App\\Controller\\CommandeController::userindex()', $container);
    }
}
