<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerprocessPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jJdX_Na.App\Controller\PaymentController::processPayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jJdX_Na.App\\Controller\\PaymentController::processPayment()'] = ($container->privates['.service_locator.jJdX_Na'] ?? $container->load('get_ServiceLocator_JJdXNaService'))->withContext('App\\Controller\\PaymentController::processPayment()', $container);
    }
}
