<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllersimulatePaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nSvWfxa.App\Controller\PaymentController::simulatePayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nSvWfxa.App\\Controller\\PaymentController::simulatePayment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.nSvWfxa.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.nSvWfxa": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'em' => '?',
            'urlGenerator' => '?',
        ]))->withContext('App\\Controller\\PaymentController::simulatePayment()', $container);
    }
}
