<?php

namespace ContainerB1DVwPv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ikQfIPI.App\Controller\PaymentController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ikQfIPI.App\\Controller\\PaymentController::cancel()'] = ($container->privates['.service_locator.ikQfIPI'] ?? $container->load('get_ServiceLocator_IkQfIPIService'))->withContext('App\\Controller\\PaymentController::cancel()', $container);
    }
}
