<?php

namespace Container0HbHvrx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControlleruserallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Tyk8_y.App\Controller\LivreController::userall()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5Tyk8_y'] ?? $container->load('get_ServiceLocator_5Tyk8YService'));

        if (isset($container->privates['.service_locator.5Tyk8_y.App\\Controller\\LivreController::userall()'])) {
            return $container->privates['.service_locator.5Tyk8_y.App\\Controller\\LivreController::userall()'];
        }

        return $container->privates['.service_locator.5Tyk8_y.App\\Controller\\LivreController::userall()'] = $a->withContext('App\\Controller\\LivreController::userall()', $container);
    }
}
