<?php

namespace Container0HbHvrx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jJdX_Na.App\Controller\PaymentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.jJdX_Na'] ?? $container->load('get_ServiceLocator_JJdXNaService'));

        if (isset($container->privates['.service_locator.jJdX_Na.App\\Controller\\PaymentController::index()'])) {
            return $container->privates['.service_locator.jJdX_Na.App\\Controller\\PaymentController::index()'];
        }

        return $container->privates['.service_locator.jJdX_Na.App\\Controller\\PaymentController::index()'] = $a->withContext('App\\Controller\\PaymentController::index()', $container);
    }
}
