<?php

namespace ContainerBaahzmB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pg9wzkx.App\Controller\CartController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pg9wzkx.App\\Controller\\CartController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livresRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
        ], [
            'livresRepository' => 'App\\Repository\\LivreRepository',
        ]))->withContext('App\\Controller\\CartController::index()', $container);
    }
}
