<?php

namespace ContainerBaahzmB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sZsftiP.App\Controller\UserController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sZsftiP.App\\Controller\\UserController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.sZsftiP.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.sZsftiP": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'comrep' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'comrep' => 'App\\Repository\\CommandeRepository',
        ]))->withContext('App\\Controller\\UserController::show()', $container);
    }
}
