<?php

namespace Container6sAchEX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BWSQ.0S.App\Controller\CategoriesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BWSQ.0S.App\\Controller\\CategoriesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rep' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
        ], [
            'rep' => 'App\\Repository\\CategoriesRepository',
        ]))->withContext('App\\Controller\\CategoriesController::index()', $container);
    }
}
