<?php

namespace ContainerFb8jWAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CGpsD3F.App\Controller\LivreController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CGpsD3F.App\\Controller\\LivreController::edit()'] = ($container->privates['.service_locator.CGpsD3F'] ?? $container->load('get_ServiceLocator_CGpsD3FService'))->withContext('App\\Controller\\LivreController::edit()', $container);
    }
}
