<?php

namespace ContainerMKXQW8F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllercommanderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3z3nwc2.App\Controller\CartController::commander()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3z3nwc2.App\\Controller\\CartController::commander()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livresRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'livresRepository' => 'App\\Repository\\LivreRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\CartController::commander()', $container);
    }
}
