<?php

namespace ContainerZVNSIb9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HHuFWdbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hHuFWdb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hHuFWdb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LivreController::delete' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\LivreController::all' => ['privates', '.service_locator.5Tyk8_y.App\\Controller\\LivreController::all()', 'getLivreControllerallService', true],
            'App\\Controller\\LivreController::show2' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show2()', 'getLivreControllershow2Service', true],
            'App\\Controller\\LivreController::show3' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show3()', 'getLivreControllershow3Service', true],
            'App\\Controller\\LivreController::show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\LivreController::create()', 'getLivreControllercreateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LivreController:delete' => ['privates', '.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\LivreController:all' => ['privates', '.service_locator.5Tyk8_y.App\\Controller\\LivreController::all()', 'getLivreControllerallService', true],
            'App\\Controller\\LivreController:show2' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show2()', 'getLivreControllershow2Service', true],
            'App\\Controller\\LivreController:show3' => ['privates', '.service_locator.bWeTQZr.App\\Controller\\LivreController::show3()', 'getLivreControllershow3Service', true],
            'App\\Controller\\LivreController:show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\LivreController::create()', 'getLivreControllercreateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LivreController::delete' => '?',
            'App\\Controller\\LivreController::all' => '?',
            'App\\Controller\\LivreController::show2' => '?',
            'App\\Controller\\LivreController::show3' => '?',
            'App\\Controller\\LivreController::show' => '?',
            'App\\Controller\\LivreController::create' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LivreController:delete' => '?',
            'App\\Controller\\LivreController:all' => '?',
            'App\\Controller\\LivreController:show2' => '?',
            'App\\Controller\\LivreController:show3' => '?',
            'App\\Controller\\LivreController:show' => '?',
            'App\\Controller\\LivreController:create' => '?',
        ]);
    }
}
