<?php

namespace ContainerTJ8Dwyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CGpsD3F.App\Controller\LivreController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.CGpsD3F'] ?? $container->load('get_ServiceLocator_CGpsD3FService'));

        if (isset($container->privates['.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()'])) {
            return $container->privates['.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()'];
        }

        return $container->privates['.service_locator.CGpsD3F.App\\Controller\\LivreController::delete()'] = $a->withContext('App\\Controller\\LivreController::delete()', $container);
    }
}
