<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxQHxSI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxQHxSI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxQHxSI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxQHxSI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxQHxSI\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxQHxSI',
    'container.build_id' => '597fd53d',
    'container.build_time' => 1746520390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxQHxSI');
