<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJ8Dwyx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJ8Dwyx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJ8Dwyx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJ8Dwyx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTJ8Dwyx\App_KernelDevDebugContainer([
    'container.build_hash' => 'TJ8Dwyx',
    'container.build_id' => '84c64b8c',
    'container.build_time' => 1746478165,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJ8Dwyx');
