<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKXQW8F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKXQW8F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKXQW8F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKXQW8F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKXQW8F\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKXQW8F',
    'container.build_id' => '56264ba3',
    'container.build_time' => 1747480860,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKXQW8F');
